### ISSUE TITLE
Update the AgentHeartbeat check to send a 120 second TTL to the Metricly API

### ISSUE THREAD

**Issue by Grumblesmith** [Netuitive/netuitive-windows-agent#15]
For checks running on a 60 second evaluation cycle, we should send the API a TTL of 120 by default. This will avoid checks firing and then immediately closing due to a few seconds of network latency. 
This TTL should be configurable in the conf file.

**Comment by andrewpaine** [comment]
The TTL is already configurable, though the setting is not visible by default. 
Similarly, the process/service checks TTL is also configurable but perhaps we should set the default to 120 for the same reason outlined above?

Do you think that the TTL config settings should be visible by default?

**Comment by Grumblesmith** [comment]
We expose the TTL setting by default in the linux agent. We also expose the collection interval here in the windows agent right? Conceivably someone might change that and, if they did, would need to adjust the TTL. I think we should expose it.

**Comment by andrewpaine** [comment]
Yes, we expose the collection interval but there's no need to adjust the check TTL if the agent collection interval changes since the check TTL is always a multiple of the agent collection period (default 2 for the heartbeat). The options they would see are HeartbeatTTLMultiplier (at the top level) and TTLMultiplier (on each check)

**Comment by Grumblesmith** [comment]
Is it possible to add custom checks?

**Comment by andrewpaine** [comment]
You can add any process/service check you want but the TTL has to be tied to the agent’s cycle.

**Comment by Grumblesmith** [comment]
I see. So the heartbeat multiplier and everyothercheck multiplier are separate, but both are multiples of the agent collection cycle. I still think these should be exposed in the check configs.

**Comment by Grumblesmith** [comment]
This may be out of scope for this issue, but I also think the default TTLMultiplier should be 1.1 at minimum

**Comment by andrewpaine** [comment]
Not out of scope at all. Let me change that.

**Comment by andrewpaine** [comment]
Done
